# Generated by Django 5.1.1 on 2024-09-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('departure_airport_name', models.CharField(max_length=255)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_airport_name', models.CharField(max_length=255)),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.TimeField()),
            ],
        ),
    ]
